
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.2'

_lr_method = 'LALR'

_lr_signature = 'K5\x87\xf3\xaf\xd2\x00\xc6v\xf1\xaf\x1fj\xc2\xf6\x9f'
    
_lr_action_items = {'RP':([3,6,7,8,9,],[-4,9,-2,-1,-3,]),'DEP':([1,3,6,7,8,9,],[4,-4,4,-2,-1,-3,]),'LP':([0,2,4,5,],[2,2,2,2,]),'NODEP':([1,3,6,7,8,9,],[5,-4,5,5,-1,-3,]),'ID':([0,2,4,5,],[3,3,3,3,]),'$end':([1,3,7,8,9,],[0,-4,-2,-1,-3,]),}

_lr_action = { }
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = { }
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'E':([0,2,4,5,],[1,6,7,8,]),}

_lr_goto = { }
for _k, _v in _lr_goto_items.items():
   for _x,_y in zip(_v[0],_v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = { }
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> E","S'",1,None,None,None),
  ('E -> E NODEP E','E',3,'p_e_nodep','myacc.py',11),
  ('E -> E DEP E','E',3,'p_e_dep','myacc.py',15),
  ('E -> LP E RP','E',3,'p_e_parent','myacc.py',19),
  ('E -> ID','E',1,'p_e_id','myacc.py',23),
]
