
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.2'

_lr_method = 'LALR'

_lr_signature = '\x1d\x03%\x90@\xb7\x84\xbd\xeb\xad\x99\x03\xd9)p\xb8'
    
_lr_action_items = {'RP':([3,6,9,14,18,19,20,21,22,23,24,25,27,28,29,],[-9,-10,-17,21,-14,-15,-11,-16,27,28,-13,-8,-6,-7,-12,]),'LP':([0,2,5,7,8,9,10,11,12,13,15,16,17,26,],[2,2,-3,2,-5,16,-4,2,2,2,-2,2,2,2,]),'INT':([0,2,5,7,8,10,11,12,13,15,16,17,26,],[6,6,-3,6,-5,-4,6,6,6,-2,6,6,6,]),'MOP':([1,3,6,9,14,18,19,20,21,24,25,27,28,29,],[13,-9,-10,-17,13,-14,-15,13,-16,13,-8,-6,-7,13,]),'ASSIGN':([9,],[17,]),'DEP':([1,3,6,9,14,18,19,20,21,24,25,27,28,29,],[12,-9,-10,-17,12,-14,-15,12,-16,12,12,-6,-7,12,]),'COMMA':([3,6,9,18,19,20,21,22,24,25,27,28,29,],[-9,-10,-17,-14,-15,-11,-16,26,-13,-8,-6,-7,-12,]),'STR':([0,2,5,7,8,10,11,12,13,15,16,17,26,],[3,3,-3,3,-5,-4,3,3,3,-2,3,3,3,]),'error':([0,5,7,8,10,15,16,],[8,-3,8,-5,-4,-2,23,]),'SC':([1,3,6,9,18,19,20,21,25,27,28,],[10,-9,-10,-17,-14,-15,-11,-16,-8,-6,-7,]),'NODEP':([1,3,6,9,14,18,19,20,21,24,25,27,28,29,],[11,-9,-10,-17,11,-14,11,11,-16,11,11,-6,-7,11,]),'ID':([0,2,5,7,8,10,11,12,13,15,16,17,26,],[9,9,-3,9,-5,-4,9,9,9,-2,9,9,9,]),'$end':([4,5,7,8,10,15,],[0,-3,-1,-5,-4,-2,]),}

_lr_action = { }
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = { }
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'PRGM':([0,],[4,]),'E':([0,2,7,11,12,13,16,17,26,],[1,14,1,18,19,20,24,25,29,]),'STMT':([0,7,],[5,15,]),'STMTLIST':([0,],[7,]),'LII':([16,],[22,]),}

_lr_goto = { }
for _k, _v in _lr_goto_items.items():
   for _x,_y in zip(_v[0],_v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = { }
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> PRGM","S'",1,None,None,None),
  ('PRGM -> STMTLIST','PRGM',1,'p_program','myacc.py',18),
  ('STMTLIST -> STMTLIST STMT','STMTLIST',2,'p_stmt_list','myacc.py',23),
  ('STMTLIST -> STMT','STMTLIST',1,'p_stmt_list','myacc.py',24),
  ('STMT -> E SC','STMT',2,'p_stmt','myacc.py',32),
  ('STMT -> error','STMT',1,'p_stmt_error','myacc.py',36),
  ('E -> ID LP LII RP','E',4,'p_func_call','myacc.py',42),
  ('E -> ID LP error RP','E',4,'p_func_call_error','myacc.py',48),
  ('E -> ID ASSIGN E','E',3,'p_assign','myacc.py',56),
  ('E -> STR','E',1,'p_e_str','myacc.py',64),
  ('E -> INT','E',1,'p_e_int','myacc.py',70),
  ('E -> E MOP E','E',3,'p_math_op','myacc.py',76),
  ('LII -> LII COMMA E','LII',3,'p_list_inside_grow','myacc.py',91),
  ('LII -> E','LII',1,'p_list_inside_orig','myacc.py',97),
  ('E -> E NODEP E','E',3,'p_e_nodep','myacc.py',104),
  ('E -> E DEP E','E',3,'p_e_dep','myacc.py',111),
  ('E -> LP E RP','E',3,'p_e_parenthesize','myacc.py',118),
  ('E -> ID','E',1,'p_e_id','myacc.py',123),
]
